package com.vanart.okxnotificationbot.sm;

public enum SMStates {
    NEW, WAITING, STOPPED,
    TRACKING_SHOW_INSTRUMENTS,
    TRACKING_SHOW_STEPS,
    TRACKING_CHECK_STEP,
    TRACKING_WAITING_STEP,
    TRACKING_INSTALL,
    TRACKING_CHECK_INPUT_INSTRUMENT,
    PRICE_SHOW_INSTRUMENTS,
    PRICE_CHECK_INPUT_INSTRUMENTS,
    PRICE,
    LIST,
    LIST_ITEM_OPTION_SELECTED, LIST_ITEM_REMOVE_CONFIRMATION, LIST_ITEM_REMOVE_CONFIRMATION_BUTTON_CLICKED, LIST_ITEM_REMOVE, LIST_ITEM_SELECTED
}
